apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
  - name: flask-app-config
    files:
      - configmap.yaml

patchesStrategicMerge:
- replicas.yaml
