apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base  # Path to your base configuration

configMapGenerator:
- name: flask-app-config
  literals:
  - BANNER_COLOR=yellow

patchesStrategicMerge:
- replicas.yaml  # Example patch file