apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base  # Path to your base configuration

configMapGenerator:
- name: mykustom-map
  env: config.properties

patchesStrategicMerge:
- replicas.yaml  # Example patch file