apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: devtestings/firstrepo:latest
        ports:
        - containerPort: 5002
