apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app: kustomwebapp

resources:
- deployment.yaml
- service.yaml
labels:
- includeSelectors: true
  pairs:
    app: kustomwebapp
  
commonAnnotations:
  app: mykustom-annontations

namePrefix: kustom-

nameSuffix: -v1
