apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80      # Port exposed by the service
      targetPort: 5002  # Port on the container
  type: LoadBalancer